name: metadrive
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.0
  - numpy=2.2.6
  - gymnasium=0.29.1
  - pyyaml
  - pip
  - pip:
      - metadrive-simulator==0.4.3
