name: metadrive
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.0
  - numpy=2.2.6
  - gymnasium=0.29.1
  - pyyaml
  - scipy
  - matplotlib
  - pillow
  - pip
  - pip:
      - metadrive-simulator==0.4.3
      - gpytorch==1.13
      - linear_operator==0.5.3
      - botorch==0.12.0
      - highway-env==1.9.1
